### ISSUE TITLE
Possible bug in ExecuteQuery: Inserting and reading varbinary or binary values might not execute byte array correctly

### ISSUE THREAD

**Issue by helvertti** [FrendsPlatform/Frends.Sql#19]
There has been an issue with reading byte array from SQL Server and trying to rebuild it back to PDF. The pdf file gets corrupted and cannot be opened. According to tutorial: https://morgantechspace.com/2014/05/how-to-store-and-read-byte-array-in-sql-server-using-csharp.html the task might be lacking byte array handling when data is returned and saved in.

**Comment by jefim** [comment]
Check if the same is happening in MS SQL repository and create issue for that too.

**Comment by helvertti** [comment]
This fix will be done as a community task, due to new logic and structure.
