### ISSUE TITLE
Update to use Microsoft package as driver

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.Sql#22]
NB! This is breaking change, make sure to bump major version!
--
NB! Make sure to mention the connection string change (server certificate parameter) in CHANGELOG
---
https://github.com/dotnet/SqlClient/issues/1930
RDES-52
---
Use this package: Microsoft.Data.SqlClient

**Comment by gruszja** [comment]
Assignment comment.

**Comment by MatteoDelOmbra** [comment]
@jefim  CR per favor :D
